### ISSUE TITLE
Volte

### ISSUE THREAD

**Issue by Hagendaz989** [LineageOS/android_device_motorola_nash#1]
Volte switched on cause any phone app to crash, after switched to off phone app runs with no problems.

**Comment by erfanoabdi** [comment]
Hey @Hagendaz989 thanks for reporting bugs but you need to use https://jira.lineageos.org
provide "adb logcat" with full model name of your device (dual sim or single), what rom version your are testing, ...
we need this info to investigate bugs

close this issue here and we will follow you in JIRA.

**Comment by Hagendaz989** [comment]
Understood thank you.

**Comment by Hagendaz989** [comment]
@erfanoabdi I created a issue but unfortunately didn't see the "don't create issues under regression" are you able to move it?

**Comment by npjohnson** [comment]
@Hagendaz989 please close this
